### ISSUE TITLE
Cipher support?

### ISSUE THREAD

**Issue by kentcb** [bordoley/SQLitePCL.pretty#34]
Hi,

I really love SQLitePCL.pretty and have used it quite a lot in one of my personal projects. I'd also love to use it in a new Xamarin+Android+iOS project I'm working on, but encryption of the DB is a requirement. The initial plan was to use [the SQLCipher Xamarin component](https://components.xamarin.com/gettingstarted/sqlcipher-for-xamarin-android), but this imposes its own API choices that are far less agreeable than that of SQLitePCL.pretty.

So, I'm wondering whether encryption support is hidden away somewhere and I've just not been able to find it. Can you shed any light on this?

**Comment by bordoley** [comment]
Glad you enjoy the API. I just released 1.0 that has some minor API changes, but I don't expect any further changes going forward. 

SQLitePCL.raw (the underlying shim library used by pretty to SQLite) supports SQLCipher. In your project file and the following property:

<UseSQLiteFrom>packaged\_sqlcipher</UseSQLiteFrom>

For more details see: https://github.com/ericsink/SQLitePCL.raw

**Comment by kentcb** [comment]
That seems...amazingly simple. Thanks for the info.

It leads to an obvious question however: why is it that people are paying $500 for a Xamarin component? Do you know if there's any difference between the store component and what I'll get if I use raw's cypher support?

**Comment by bordoley** [comment]
I'm not really familiar with SQLCipher. You might want to ask Eric who maintains SQLitePCL.raw. I'm guessing it has to with the open source vs. commercial support contract. See: https://www.zetetic.net/sqlcipher/support/

**Comment by bordoley** [comment]
@ericsink can you provide any insight on @kentcb's question?

**Comment by ericsink** [comment]
(1)  Level of support would be a big difference.  Zetetic are the authors of SQLCipher, so getting support from them is the best option.  The SQLitePCL.raw bundling of SQLCipher comes with no promise of support at all.

(2)  The SQLCipher feature of SQLitePCL.raw is reasonably new and not well tested.  One user is having trouble with it right now, and I'm trying to diagnose whether his config is messed up or if my bundling has some sort of problem.

(3)  There may be other differences between the feature in SQLitePCL.raw and what is included in the Xamarin component from Zetetic.  I don't know.

**Comment by kentcb** [comment]
thanks for the info @ericsink 

Presumably there's no way to have the raw/pretty APIs magically work against the Zetetic SQLite bundling?

**Comment by ericsink** [comment]
I suppose that could probably be done, but it wouldn't be easy, much less "magical".

**Comment by bordoley** [comment]
@kentcb You could attempt to take a Zetetic prebuild sqlite binary for iOS/Android and replace the per platform ones bundled with SQLitePCL.raw with them. Definitely would be worth experimenting with. Make sure the SQLite version is relatively recent (> 3.8) as pretty utilizes lots of newer features.

Also if you do go down this path, let me know if a SQLCiipher helper package would be helpful. It doesn't appear the at SQLitePCL.raw explicitly exposes the  SQLCipher c api, but it would be possible to add nicer functions in a pretty extension for the SQLCipher pragmas.
