### ISSUE TITLE
IResultSetValue.ColumnInfo access throws exception.

### ISSUE THREAD

**Issue by alexpetin** [bordoley/SQLitePCL.pretty#35]
Hello!

I cant access result set column names.
Access to IResultSetValue.ColumnInfo throws "System.EntryPointNotFoundException: sqlite3_column_database_name".

Xamarin.Android, Xamarin.iOS. 

Is there a way to access columns in result set by names, not only by number?

**Comment by bordoley** [comment]
What operating system are you experiencing this failure on? SQLitePCL.pretty is dependent on numerous features that are only available in more recent versions of SQLite, but I would suspect that at least the most current versions of iOS and android would have a new enough version. 

Generally speaking, I would recommend at least on android shipping your own version of SQLite to guarantee that the version of SQLite is recent enough. [SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw) (which this library depends on to directly wrap the SQLite API) provides the ability to package a version of SQLite it provides at build time. @ericsink, can you provide pointers to the current supported way to do this? 

The ColumnInfo instance returned by IResultSetValue.ColumnInfo depends upon the underlying SQLite implementation supporting the sqlite3_column_database_name function. See: 

https://github.com/bordoley/SQLitePCL.pretty/blob/92835955ce59cd0f60745f7bece06fc1f516a19a/SQLitePCL.pretty/ColumnInfo.cs#L83

If using a packaged version of SQLite is really not an option for you, I'd be open to accepting a pull request that wraps that API call in a try catch, and defaulting the database name to empty string.

**Comment by alexpetin** [comment]
It occurs at Android: API 17 & 23; iOS: 8.1 & 9.3.
Probably all versions includes SQLite compiled without this API.

https://www.sqlite.org/c3ref/column_database_name.html :
"These APIs are only available if the library was compiled with the SQLITE_ENABLE_COLUMN_METADATA C-preprocessor symbol."

So, the problem is not in not recent version of SQLite used in Android and iOS - probably Google and Apple thinks that this API does not needed.

Yes, the problem may be resolved by using SQLitePCL.raw plugins with own version of SQLite. The current version includes this API, but is it guaranteed for the future versions?

So, I think it would be more correct to add a checking for all of these functions availability:
sqlite3_column_database_name(),
sqlite3_column_origin_name(),
sqlite3_column_table_name().

Unfortunately I'm not familiar with creating pull requests (yes, lol:) and absolutely out of time right now to research. Could you please to make it yourself? I can help with testing of this issue, if needed.

Btw, big thanks for your work on this library, it's really great!

**Comment by ericsink** [comment]
You'll need to package a SQLite library anyway to be compatible with Android N.

For SQLitePCL.raw 0.9.x, add this nuget package:

SQLitePCL.plugin.sqlite3.android

and add this line of initialization code:

SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_esqlite3())

Yes, the SQLite native code I compile for this plugin will always be compiled with SQLITE_ENABLE_COLUMN_METADATA.

**Comment by alexpetin** [comment]
I've included SQLitePCL.plugin.sqlite3.ios_unified to the Xamarin.ios project. It gives a warning:

Warning: Native linking warning: warning: object file (/Users/axp/Library/Caches/Xamarin/mtbs/builds/JerichoiOS/8f8ba59e228e737f773974b1c1909111/obj/iPhone/Debug/mtouch-cache/esqlite3.a(sqlite3.c.o)) was built for newer iOS version (9.2) than being linked (8.1)

What I can do with it? My app should be compatible with 8.1+ iOS...

**Comment by bordoley** [comment]
FYI, I'm looking into updating to the SQLitePCLraw 1.0 next week. Will try to address this then as well.

**Comment by bordoley** [comment]
I added try catch blocks around the functions which depend upon the SQLITE_ENABLE_COLUMN_METADATA flag.
