### ISSUE TITLE
Support Compiling on .NET v3.5?

### ISSUE THREAD

**Issue by spaceman5** [bordoley/SQLitePCL.pretty#42]
Hi

Is it possible to make SQLitePCL.pretty's code to be able to compile under .NET v3.5?

**Comment by bordoley** [comment]
I'm not actively maintaining SQLitePCL.pretty, but I'm fairly certain the answer to this question is no. You could try compiling the core library itself, but the async library and the orm most certainly depend on features only available in newer .net versions. If you do get this working, you can submit a PR, but I'm not planning on doing new releases myself.

**Comment by spaceman5** [comment]
Hi

Thank you very much for your reply.

>You could try compiling the core library itself,
>but the async library and the orm most certainly depend on features only available in newer .net versions.

Actually I don't need the async and ORM..
So I wlll try and see If I can compile the core library..

Thank you
